### PR TITLE
Fix docblock issues

### PR DESCRIPTION
**Pull request by mdeboer**
Issues with missing use statements prevented code completion from working correctly. Aside from that I cleaned up some docblocks but you're free to dismiss those edits if you like.

### CODE REVIEW

**Comment by ramsey** [comment]
Thank you for contributing! 🎉

Looks like PHP CodeSniffer found some problems with whitespace at the end of lines. Please clean those up, and I'll merge this in. Thanks!

**Comment by mdeboer** [comment]
Ah I see, these days I solely rely on a `.editorconfig` being present, I forget not all projects have them. I'll fix it and commit the changes 👍 

And thank you for an amazing library! 😀

**Comment by mdeboer** [comment]
I fixed the issues and took the liberty of adding a phpcs.xml ruleset file. This allows you to run `phpcs` without further arguments like directories and rulesets and guarantees that all tools use the same configuration (IDEs, travis...).

**Comment by ramsey** [comment]
Thank you for contributing! 🎉

**Pull request merged**
